# Generated by Django 2.1.1 on 2018-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNo', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('payToken', models.CharField(max_length=23)),
            ],
        ),
    ]
