# Generated by Django 2.1.1 on 2018-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNo',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
