# Generated by Django 2.1.1 on 2018-11-11 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file_size', models.BigIntegerField()),
                ('uploaded_file_version', models.CharField(max_length=255, null=True)),
                ('uploaded_filename', models.CharField(max_length=255)),
                ('scale_factor', models.SmallIntegerField(choices=[(2, 'x2'), (4, 'x4')], default=2)),
                ('progress_status', models.CharField(choices=[('PE', 'Pending'), ('IP', 'In progress'), ('FI', 'Finished')], default='PE', max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
