# Generated by Django 2.1.1 on 2018-11-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='progress_status',
            field=models.CharField(choices=[('PE', '대기중'), ('IP', '처리중'), ('FI', '처리 완료')], default='PE', max_length=2),
        ),
    ]
