# Generated by Django 2.1.1 on 2018-10-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file_size', models.BigIntegerField()),
                ('uploaded_file_version', models.CharField(max_length=255)),
                ('progress_status', models.CharField(choices=[('IP', 'In progress'), ('FI', 'Finished')], default='IP', max_length=2)),
            ],
        ),
    ]
