# Generated by Django 2.1.1 on 2018-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosr', '0002_uploadedfile_uploaded_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_file_version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
