# Generated by Django 2.1.1 on 2018-11-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosr', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='scale_factor',
            field=models.SmallIntegerField(choices=[(2, 'x2'), (4, 'x4')], default=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='progress_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('IP', 'In progress'), ('FI', 'Finished')], default='PE', max_length=2),
        ),
    ]
