# Generated by Django 2.1.1 on 2018-11-04 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videosr', '0005_auto_20181103_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='owner',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
